### ISSUE TITLE
"Sandbox Testing" checkbox is not necessary

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give-iATS#3]
## Issue Overview

When Give is in "Test Mode" payments processed should go to the sandbox. There doesn't need to be an additional checkbox option for it:

![2016-10-27_14-54-15](https://cloud.githubusercontent.com/assets/1571635/19787000/848cf0c4-9c55-11e6-8b65-a73dc3e3d8aa.png)

**Comment by ravinderk** [comment]
@DevinWalker This has been fixed.
For ref: https://github.com/WordImpress/Give-iATS/commit/79cc5f66cc8b75ba60d0bb2a645bdfa4419c6af0

**Comment by DevinWalker** [comment]
Thanks @ravinderk 🤖
