### ISSUE TITLE
Implement Tracking code

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-iATS#4]
Got this info from the iATS team on how we can add our custom tracking code into our Add-on. 

Depending on your current usage of these fields, here are some options to consider placing the identifier string:
  1. If you’re not passing a value in the comment field
      a. Pass the identifier in the comment field
  2. Otherwise consider using the invoice number field
    a. If you’re not passing a value in the invoice number field 
      * Pass the identifier in the invoiceNum field 
    b. Otherwise 
      * Add the identifier as the prefix (e.g. give-0012) 
 
So, in our [PHP API wrapper (Processlink.php) starting at line 88](https://github.com/iATSPayments/PHP/blob/master/lib/ProcessLink.php#L88-L121):

We could either prefix the `invoiceNum` parameter, or add it into the `comment` parameter. I'd prefer the comment parameter to keep it out of Donors' eyes.
 
```
   * Process a credit card transaction and return Customer Code.
   *
   * @param array $parameters
   *   An associative array with the following possible values.
   *     'customerIPAddress' => '' 
   *     'invoiceNum' => '00000001'
   *     'ccNum' => '4222222222222220' 
   *     'ccExp' => '12/17'
   *     'firstName' => 'Test' 
   *     'lastName' => 'Account'
   *     'address' => '1234 Any Street'
   *     'city' => 'Schenectady'
   *     'state' => 'NY' 
   *     'zipCode' => '12345' 
   *     'cvv2' => '000' 
   *     'total' => '5'
   *     'comment' => 'string' // Force this to be "givewp"
   *     'title' => 'string'
   *     'phone' => '1234567890'
```

**Comment by ravinderk** [comment]
@mathetos This has been fixed.
For ref: https://github.com/WordImpress/Give-iATS/commit/f35edee5ba7232f33e4c2a4786d185727e829936

**Comment by DevinWalker** [comment]
That's nice @ravinderk thanks
